import express from "express";
import { authorizeRoles } from "../middleware/verifyRole.js";
import authenticateUser from "../middleware/verifyJWT.js";
import { registerUser,getUserProfile, verifyOtp, loginUser,assignLoginToEmployee ,logOutUser,changeUserPassword,forgotPassword,resetUserPassword,checkLoginStatus,updateUserProfile,contactUs} from "../controller/user.controler.js";
import { strictLimiter, mediumLimiter, relaxedLimiter } from "../middleware/RateLimit-Frequency.js";
const router = express.Router();
// add relaxedLimiter to all
router.post("/register",mediumLimiter, registerUser);
router.post("/verify-otp", mediumLimiter, verifyOtp);
router.post("/login-user", mediumLimiter, loginUser);
router.post("/assign-login/:employeeId",relaxedLimiter, assignLoginToEmployee);
router.post("/logout",mediumLimiter, authenticateUser, logOutUser);
router.post("/change-password", relaxedLimiter, authenticateUser, changeUserPassword);
router.post("/forgot-password", relaxedLimiter, forgotPassword);
router.post("/reset-password/:token",relaxedLimiter, resetUserPassword);
router.get("/check-login", relaxedLimiter, checkLoginStatus);
router.get("/profile",relaxedLimiter, authenticateUser, getUserProfile);
router.put("/update-profile", relaxedLimiter, authenticateUser, updateUserProfile);
router.post("/contact-us",strictLimiter, contactUs);
export default router;
